---
sudo: required
language: python

services:
  - docker

install:
  - >-
      if [ "$SCENARIO" = interpreter-py2 ]; then
          pip install "ome-ansible-molecule<0.5";
      fi
  # Ansible 2.6 has problems when the remote python version is 3
  - >-
      if [ "$SCENARIO" = interpreter-py3 ]; then
          pip install ansible==2.8.3 molecule==2.22 docker==4.1.0;
      fi

script:
  - molecule test -s $SCENARIO

env:
  - SCENARIO=interpreter-py2
  - SCENARIO=interpreter-py3

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
