---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
    yamllint .
    ansible-lint
    flake8
platforms:
  - name: interpreter-py2-c7
    image: rockylinux:9
    groups:
      - py2
  - name: interpreter-py2-u2204
    image: ubuntu:22.04
    groups:
      - py2
provisioner:
  name: ansible
  playbooks:
    converge: ../resources/playbook.yml
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      py2:
        ansible_python_interpreter: python2

scenario:
  name: interpreter-py2
verifier:
  name: testinfra
  directory: ../resources/tests/
