---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  # Using the Python 3 for ansible on CentOS 7 requires other changes
  # so ignore for now
  # - name: interpreter-py3-c7
  #   image: centos:7
  #   groups:
  #     - py3
  - name: interpreter-py3-u1804
    image: ubuntu:18.04
    groups:
      - py3

provisioner:
  name: ansible
  playbooks:
    converge: ../resources/playbook.yml
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      py3:
        ansible_python_interpreter: python3

scenario:
  name: interpreter-py3
verifier:
  name: testinfra
  directory: ../resources/tests/
  lint:
    name: flake8
