---
name: Molecule
# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
  schedule:
    - cron: '29 21 * * 0'

jobs:

  list-scenarios:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.listscenarios.outputs.scenarios }}
    steps:
      - uses: actions/checkout@v2
      - id: listscenarios
        uses: ome/action-ansible-molecule-list-scenarios@main

  test:
    name: Test
    needs:
      - list-scenarios
    runs-on: ubuntu-18.04
    strategy:
      # Keep running so we can see if other tests pass
      fail-fast: false
      matrix:
        scenario: ${{fromJson(needs.list-scenarios.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      # Ansible 2.6 has problems when the remote python version is 3
      - name: Install ome-ansible-molecule
        run: |
          if [ $SCENARIO = interpreter-py2 ]; then
            python -mpip install 'ome-ansible-molecule==0.4.*'
          else
            python -mpip install ansible==2.8.3 molecule==2.22 docker==4.4.1
          fi
        env:
          SCENARIO: ${{ matrix.scenario }}
      - uses: ome/action-ome-ansible-molecule@main
        with:
          manage-virtualenv: "false"
          scenario: ${{ matrix.scenario }}

# notifications:
#   webhooks: https://galaxy.ansible.com/api/v1/notifications/
